#!/usr/bin/env bash
set -euo pipefail

readonly issue_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly output="$issue_dir/README.md"
tmp="$(mktemp "${TMPDIR:-/tmp}/ukiel-issues-index.XXXXXX")"
trap 'rm -f -- "$tmp"' EXIT

extract_field() {
    local file=$1
    local field=$2
    awk -v field="$field" '
        $0 ~ "^- \\*\\*" field "s?:\\*\\*" {
            sub("^- \\*\\*" field "s?:\\*\\*[[:space:]]*", "")
            print
            exit
        }
    ' "$file"
}

escape_cell() {
    local value=$1
    value=${value//$'\r'/}
    value=${value//$'\n'/ }
    value=${value//|/\\|}
    printf '%s' "$value"
}

short_status() {
    local value=${1//\*/}
    case "$value" in
        Open*) printf 'Open' ;;
        Resolved*) printf 'Resolved' ;;
        Accepted*) printf 'Accepted' ;;
        Closed*) printf 'Closed' ;;
        Blocked*) printf 'Blocked' ;;
        *) printf '%s' "${value%% —*}" ;;
    esac
}

short_severity() {
    local value=${1//\*/}
    printf '%s' "${value%% (*}"
}

{
    printf '%s\n\n' '# Issue index'
    printf '%s\n\n' '<!-- Generated by ./generate-index.sh; do not edit by hand. -->'
    printf '%s\n\n' 'Create new issues from [TEMPLATE.md](TEMPLATE.md), then run `docs/issues/generate-index.sh` from any working directory.'
    printf '%s\n' '| ID | Issue | Severity | Status | Components |'
    printf '%s\n' '|---:|---|---|---|---|'

    shopt -s nullglob
    files=("$issue_dir"/[0-9][0-9][0-9][0-9]-*.md)
    if ((${#files[@]} == 0)); then
        printf '%s\n' '| — | No issues found | — | — | — |'
    else
        while IFS= read -r file; do
            base=${file##*/}
            id=${base%%-*}
            title=$(awk '/^# / { sub(/^# /, ""); print; exit }' "$file")
            title=${title#"$id — "}
            severity=$(extract_field "$file" 'Severity')
            status=$(extract_field "$file" 'Status')
            components=$(extract_field "$file" 'Component')

            printf '| %s | [%s](%s) | %s | %s | %s |\n' \
                "$(escape_cell "$id")" \
                "$(escape_cell "$title")" \
                "$(escape_cell "$base")" \
                "$(escape_cell "$(short_severity "${severity:-Unspecified}")")" \
                "$(escape_cell "$(short_status "${status:-Unspecified}")")" \
                "$(escape_cell "${components:-Unspecified}")"
        done < <(printf '%s\n' "${files[@]}" | LC_ALL=C sort)
    fi
} > "$tmp"

mv -- "$tmp" "$output"
trap - EXIT
