//! A stable, named, versioned PRNG.
//!
//! Determinism is the product here, so the generator cannot borrow randomness
//! from anywhere it does not control. `thread_rng` reseeds per process. A
//! library's `sample` helper may change algorithm across a semver-compatible
//! bump, silently producing a different fixture from the same seed. Iterating a
//! `HashMap` is randomized per process by design. Any one of those turns
//! "generated from seed 7" into a sentence with no meaning.
//!
//! So: one algorithm, written out here, named in the manifest
//! ([`ALGORITHM`]), and pinned by a golden-sequence test. If the numbers ever
//! change, that test fails and the version string has to change with them —
//! which is exactly the coupling we want, because a fixture generated by a
//! different PRNG is a different fixture.
//!
//! SplitMix64 (Steele et al., "Fast splittable pseudorandom number generators").
//! It is not cryptographic and does not need to be: it needs to be uniform,
//! fast, and *written down*.

/// Named in every manifest. Change the numbers, change this string.
pub const ALGORITHM: &str = "splitmix64/v1";

#[derive(Debug, Clone)]
pub struct StableRng {
    state: u64,
}

impl StableRng {
    /// A root stream from the user's seed.
    pub fn new(seed: u64) -> Self {
        StableRng { state: seed }
    }

    /// A **domain-separated** child stream.
    ///
    /// Every phase of compilation draws from its own stream, so adding a draw to
    /// one phase cannot shift the numbers every later phase sees. Without this,
    /// inserting a single extra `next_u64` in tenant resampling would silently
    /// rewrite the graph, the IDs, and every generated row — and the only symptom
    /// would be that yesterday's digests stopped reproducing.
    pub fn stream(seed: u64, domain: &str) -> Self {
        // FNV-1a over the domain name, mixed into the seed. Any injective-enough
        // mix works; what matters is that it is fixed and written here.
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        for b in domain.as_bytes() {
            h ^= *b as u64;
            h = h.wrapping_mul(0x0000_0100_0000_01b3);
        }
        StableRng {
            state: mix(seed ^ h),
        }
    }

    pub fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        mix(self.state)
    }

    /// Uniform in `[0, n)`, via Lemire's multiply-shift with rejection.
    ///
    /// Rejection, not modulo: `next_u64() % n` is biased toward small values
    /// whenever `n` does not divide 2^64, and the bias lands precisely on the
    /// low-index tenants and parts that a skewed fixture is most sensitive to.
    pub fn below(&mut self, n: u64) -> u64 {
        assert!(n > 0, "below(0) has no answer");
        let mut x = self.next_u64();
        let mut m = (x as u128) * (n as u128);
        let mut l = m as u64;
        if l < n {
            let threshold = n.wrapping_neg() % n;
            while l < threshold {
                x = self.next_u64();
                m = (x as u128) * (n as u128);
                l = m as u64;
            }
        }
        (m >> 64) as u64
    }

    /// Uniform in `[lo, hi]`, inclusive.
    pub fn range_inclusive(&mut self, lo: u64, hi: u64) -> u64 {
        assert!(lo <= hi);
        lo + self.below(hi - lo + 1)
    }

    /// Uniform in `[0, 1)`, from the top 53 bits — the exactly-representable
    /// mantissa of an f64. Taking the low bits instead would quantize the result
    /// unevenly.
    pub fn next_f64(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 * (1.0 / (1u64 << 53) as f64)
    }

    /// In-place Fisher-Yates. The one shuffle in the tool.
    pub fn shuffle<T>(&mut self, items: &mut [T]) {
        for i in (1..items.len()).rev() {
            let j = self.below(i as u64 + 1) as usize;
            items.swap(i, j);
        }
    }

    /// `k` distinct values from `[lo, hi]` — Floyd's algorithm, then sorted.
    ///
    /// Floyd rather than shuffling the whole interval: the tenant key universe is
    /// ~3.6x the tenant count, and at the `shape` tier that is half a million
    /// candidates to draw ~142k from. Floyd is O(k) in both time and space.
    pub fn sample_distinct(&mut self, lo: u64, hi: u64, k: usize) -> Vec<u64> {
        let n = hi - lo + 1;
        assert!(k as u64 <= n, "cannot draw {k} distinct values from {n}");
        let mut chosen = std::collections::HashSet::with_capacity(k);
        let mut out = Vec::with_capacity(k);
        for j in (n - k as u64)..n {
            let t = lo + self.below(j + 1);
            let v = if chosen.contains(&t) { lo + j } else { t };
            chosen.insert(v);
            out.push(v);
        }
        // Sorted, not in draw order: a HashSet's iteration order is not ours to
        // depend on, and the caller wants ascending IDs anyway.
        out.sort_unstable();
        out
    }

    /// Index into `weights` with probability proportional to its entry.
    ///
    /// Linear scan. The vocabularies are tens of entries, so an alias table would
    /// be more code for no measurable gain — and this way the draw is obviously
    /// the one the manifest describes.
    pub fn weighted(&mut self, weights: &[f64]) -> usize {
        let total: f64 = weights.iter().sum();
        let mut r = self.next_f64() * total;
        for (i, w) in weights.iter().enumerate() {
            r -= w;
            if r < 0.0 {
                return i;
            }
        }
        weights.len() - 1
    }
}

fn mix(mut z: u64) -> u64 {
    z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    z ^ (z >> 31)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The golden sequence. If this fails, the generator produces a different
    /// fixture from the same seed than it did yesterday — so [`ALGORITHM`] must
    /// change too, and every recorded digest in the repository is stale.
    #[test]
    fn splitmix64_golden_sequence() {
        let mut rng = StableRng::new(0);
        let got: Vec<u64> = (0..8).map(|_| rng.next_u64()).collect();
        assert_eq!(
            got,
            vec![
                0xe220_a839_7b1d_cdaf,
                0x6e78_9e6a_a1b9_65f4,
                0x06c4_5d18_8009_454f,
                0xf88b_b8a8_724c_81ec,
                0x1b39_896a_51a8_749b,
                0x53cb_9f0c_747e_a2ea,
                0x2c82_9abe_1f45_32e1,
                0xc584_133a_c916_ab3c,
            ],
            "splitmix64 reference vectors for seed 0"
        );
    }

    #[test]
    fn streams_are_domain_separated_and_reproducible() {
        let a: Vec<u64> = (0..4)
            .map(|_| StableRng::stream(7, "tenants").next_u64())
            .collect();
        let b: Vec<u64> = (0..4)
            .map(|_| StableRng::stream(7, "parts").next_u64())
            .collect();
        assert_ne!(a, b, "different domains must not share a stream");

        // Same seed + domain, twice: identical. This is the whole promise.
        let mut x = StableRng::stream(7, "tenants");
        let mut y = StableRng::stream(7, "tenants");
        for _ in 0..64 {
            assert_eq!(x.next_u64(), y.next_u64());
        }
    }

    #[test]
    fn below_is_uniform_and_in_range() {
        let mut rng = StableRng::stream(1, "uniform");
        let mut counts = [0usize; 8];
        for _ in 0..80_000 {
            let v = rng.below(8);
            assert!(v < 8);
            counts[v as usize] += 1;
        }
        // 10k expected per bucket; a biased modulo would skew the low buckets
        // measurably. 5% is far outside sampling noise at this n and far inside
        // what a real bias would produce.
        for (i, c) in counts.iter().enumerate() {
            assert!(
                (*c as f64 - 10_000.0).abs() < 500.0,
                "bucket {i} got {c}, expected ~10000"
            );
        }
    }

    #[test]
    fn sample_distinct_is_distinct_sorted_and_within_bounds() {
        let mut rng = StableRng::stream(3, "ids");
        let v = rng.sample_distinct(1, 1000, 300);
        assert_eq!(v.len(), 300);
        assert!(v.windows(2).all(|w| w[0] < w[1]), "sorted and distinct");
        assert!(v.iter().all(|x| (1..=1000).contains(x)));

        // The degenerate case the tenant draw hits when the universe is tight.
        let all = StableRng::stream(3, "ids").sample_distinct(5, 9, 5);
        assert_eq!(all, vec![5, 6, 7, 8, 9]);
    }

    #[test]
    fn shuffle_is_a_permutation_and_deterministic() {
        let mut a: Vec<u32> = (0..64).collect();
        let mut b = a.clone();
        StableRng::stream(9, "s").shuffle(&mut a);
        StableRng::stream(9, "s").shuffle(&mut b);
        assert_eq!(a, b, "same seed, same permutation");
        assert_ne!(a, (0..64).collect::<Vec<_>>(), "actually shuffled");
        let mut sorted = a.clone();
        sorted.sort_unstable();
        assert_eq!(sorted, (0..64).collect::<Vec<_>>(), "a permutation");
    }

    #[test]
    fn weighted_respects_the_weights() {
        let mut rng = StableRng::stream(4, "w");
        let weights = [10.0, 1.0, 1.0];
        let mut counts = [0usize; 3];
        for _ in 0..12_000 {
            counts[rng.weighted(&weights)] += 1;
        }
        assert!(counts[0] > 9_000, "the 10:1:1 entry dominates: {counts:?}");
        assert!(counts[1] > 500 && counts[2] > 500, "tails present");
    }
}
