CREATE TABLE posthog.sharded_events
(
    `uuid` UUID,
    `event` String,
    `properties` String CODEC(ZSTD(3)),
    `timestamp` DateTime64(6, 'UTC'),
    `team_id` Int64,
    `distinct_id` String,
    `elements_chain` String,
    `created_at` DateTime64(6, 'UTC'),
    `person_id` UUID,
    `person_properties` String CODEC(ZSTD(3)),
    `group0_properties` String CODEC(ZSTD(3)),
    `group1_properties` String CODEC(ZSTD(3)),
    `group2_properties` String CODEC(ZSTD(3)),
    `group3_properties` String CODEC(ZSTD(3)),
    `group4_properties` String CODEC(ZSTD(3)),
    `$group_0` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$group_0'), '^"|"$', '') COMMENT 'column_materializer::$group_0',
    `$group_1` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$group_1'), '^"|"$', '') COMMENT 'column_materializer::$group_1',
    `$group_2` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$group_2'), '^"|"$', '') COMMENT 'column_materializer::$group_2',
    `$group_3` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$group_3'), '^"|"$', '') COMMENT 'column_materializer::$group_3',
    `$group_4` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$group_4'), '^"|"$', '') COMMENT 'column_materializer::$group_4',
    `$window_id` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$window_id'), '^"|"$', '') COMMENT 'column_materializer::$window_id',
    `$session_id` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$session_id'), '^"|"$', '') COMMENT 'column_materializer::$session_id',
    `_timestamp` DateTime,
    `_offset` UInt64,
    `person_created_at` DateTime64(3),
    `group0_created_at` DateTime64(3),
    `group1_created_at` DateTime64(3),
    `group2_created_at` DateTime64(3),
    `group3_created_at` DateTime64(3),
    `group4_created_at` DateTime64(3),
    `mat_se_label` String MATERIALIZED replaceRegexpAll(JSONExtractRaw(properties, 'se_label'), '^"|"$', ''),
    `mat_se_category` String MATERIALIZED replaceRegexpAll(JSONExtractRaw(properties, 'se_category'), '^"|"$', ''),
    `mat_first_visit` Nullable(String) MATERIALIZED replaceRegexpAll(nullIf(nullIf(JSONExtractRaw(properties, 'first_visit'), ''), 'null'), '^"|"$', ''),
    `mat_first_visit_2` Nullable(String) MATERIALIZED replaceRegexpAll(nullIf(nullIf(JSONExtractRaw(properties, 'first_visit'), ''), 'null'), '^"|"$', ''),
    `inserted_at` Nullable(DateTime64(6, 'UTC')) DEFAULT now64(),
    `person_mode` Enum8('full' = 0, 'propertyless' = 1, 'force_upgrade' = 2),
    `elements_chain_href` String MATERIALIZED extract(elements_chain, '(?::|")href="(.*?)"'),
    `elements_chain_texts` Array(String) MATERIALIZED arrayDistinct(extractAll(elements_chain, '(?::|")text="(.*?)"')),
    `elements_chain_elements` Array(Enum8('a' = 1, 'button' = 2, 'form' = 3, 'input' = 4, 'select' = 5, 'textarea' = 6, 'label' = 7)) MATERIALIZED arrayDistinct(extractAll(elements_chain, '(?:^|;)(a|button|form|input|select|textarea|label)(?:\\.|$|:)')),
    `elements_chain_ids` Array(String) MATERIALIZED arrayDistinct(extractAll(elements_chain, '(?::|")attr_id="(.*?)"')),
    `properties_group_custom` Map(String, String) MATERIALIZED mapSort(mapFilter((key, _) -> ((key NOT LIKE '$%') AND (key NOT IN ('token', 'distinct_id', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term', 'gclid', 'gad_source', 'gclsrc', 'dclid', 'gbraid', 'wbraid', 'fbclid', 'msclkid', 'twclid', 'li_fat_id', 'mc_cid', 'igshid', 'ttclid', 'rdt_cid'))), CAST(JSONExtractKeysAndValues(properties, 'String'), 'Map(String, String)'))) CODEC(ZSTD(1)),
    `properties_group_feature_flags` Map(String, String) MATERIALIZED mapSort(mapFilter((key, _) -> (key LIKE '$feature/%'), CAST(JSONExtractKeysAndValues(properties, 'String'), 'Map(String, String)'))) CODEC(ZSTD(1)),
    `is_deleted` Bool,
    `person_properties_map_custom` Map(String, String) MATERIALIZED mapSort(mapFilter((key, _) -> (key NOT LIKE '$%'), CAST(JSONExtractKeysAndValues(person_properties, 'String'), 'Map(String, String)'))) CODEC(ZSTD(1)),
    `$session_id_uuid` Nullable(UInt128) MATERIALIZED toUInt128(JSONExtract(properties, '$session_id', 'Nullable(UUID)')),
    `consumer_breadcrumbs` Array(String),
    `properties_map_ephemeral` Map(String, String) EPHEMERAL CAST(JSONExtractKeysAndValues(properties, 'String'), 'Map(String, String)'),
    `person_properties_map_ephemeral` Map(String, String) EPHEMERAL CAST(JSONExtractKeysAndValues(person_properties, 'String'), 'Map(String, String)'),
    `properties_group_ai` Map(String, String) MATERIALIZED mapSort(mapFilter((key, _) -> ((key LIKE '$ai_%') AND (key NOT IN ('$ai_input', '$ai_input_state', '$ai_output', '$ai_output_choices', '$ai_output_state', '$ai_tools'))), CAST(JSONExtractKeysAndValues(properties, 'String'), 'Map(String, String)'))) CODEC(ZSTD(1)),
    `mat_$host` String MATERIALIZED replaceRegexpAll(JSONExtractRaw(properties, '$host'), '^"|"$', ''),
    `mat_email` String MATERIALIZED replaceRegexpAll(JSONExtractRaw(properties, 'email'), '^"|"$', ''),
    `mat_$lib` String MATERIALIZED replaceRegexpAll(JSONExtractRaw(properties, '$lib'), '^"|"$', ''),
    `mat_$process_person_profile` String MATERIALIZED replaceRegexpAll(JSONExtractRaw(properties, '$process_person_profile'), '^"|"$', ''),
    `mat_$ai_trace_id` Nullable(String) MATERIALIZED JSONExtract(properties, '$ai_trace_id', 'Nullable(String)'),
    `mat_historical_migration` Nullable(String) DEFAULT JSONExtract(properties, 'historical_migration', 'Nullable(String)'),
    `mat_$ai_session_id` Nullable(String) MATERIALIZED JSONExtract(properties, '$ai_session_id', 'Nullable(String)'),
    `mat_$ai_is_error` Nullable(String) MATERIALIZED JSONExtract(properties, '$ai_is_error', 'Nullable(String)'),
    `dmat_string_0` Nullable(String),
    `dmat_string_1` Nullable(String),
    `dmat_string_2` Nullable(String),
    `dmat_string_3` Nullable(String),
    `dmat_string_4` Nullable(String),
    `dmat_string_5` Nullable(String),
    `dmat_string_6` Nullable(String),
    `dmat_string_7` Nullable(String),
    `dmat_string_8` Nullable(String),
    `dmat_string_9` Nullable(String),
    `historical_migration` Bool,
    `mat_$ai_prompt_name` Nullable(String) MATERIALIZED JSONExtract(properties, '$ai_prompt_name', 'Nullable(String)'),
    `mat_name` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, 'name'), '^"|"$', ''),
    `mat_$screen_name` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$screen_name'), '^"|"$', ''),
    `mat_$email` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$email'), '^"|"$', ''),
    `mat_UserName` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, 'UserName'), '^"|"$', ''),
    `mat_username` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, 'username'), '^"|"$', ''),
    `mat_Email` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, 'Email'), '^"|"$', ''),
    `mat_$current_url` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$current_url'), '^"|"$', ''),
    `mat_Name` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, 'Name'), '^"|"$', ''),
    `mat_Username` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, 'Username'), '^"|"$', ''),
    `mat_$ai_experiment_id` Nullable(String) DEFAULT JSONExtract(properties, '$ai_experiment_id', 'Nullable(String)'),
    `mat_$exception_values` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$exception_values'), '^"|"$', ''),
    `mat_$exception_types` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$exception_types'), '^"|"$', ''),
    `mat_$exception_issue_id` String DEFAULT replaceRegexpAll(JSONExtractRaw(properties, '$exception_issue_id'), '^"|"$', ''),
    INDEX minmax_inserted_at coalesce(inserted_at, _timestamp) TYPE minmax GRANULARITY 1,
    INDEX properties_group_custom_keys_bf mapKeys(properties_group_custom) TYPE bloom_filter GRANULARITY 1,
    INDEX properties_group_custom_values_bf mapValues(properties_group_custom) TYPE bloom_filter GRANULARITY 1,
    INDEX properties_group_feature_flags_keys_bf mapKeys(properties_group_feature_flags) TYPE bloom_filter GRANULARITY 1,
    INDEX properties_group_feature_flags_values_bf mapValues(properties_group_feature_flags) TYPE bloom_filter GRANULARITY 1,
    INDEX is_deleted_idx is_deleted TYPE minmax GRANULARITY 1,
    INDEX person_properties_map_custom_keys_bf mapKeys(person_properties_map_custom) TYPE bloom_filter GRANULARITY 1,
    INDEX person_properties_map_custom_values_bf mapValues(person_properties_map_custom) TYPE bloom_filter GRANULARITY 1,
    INDEX properties_group_ai_keys_bf mapKeys(properties_group_ai) TYPE bloom_filter GRANULARITY 1,
    INDEX properties_group_ai_values_bf mapValues(properties_group_ai) TYPE bloom_filter GRANULARITY 1,
    INDEX `minmax_mat_$host` `mat_$host` TYPE minmax GRANULARITY 1,
    INDEX minmax_mat_email mat_email TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$lib` `mat_$lib` TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$process_person_profile` `mat_$process_person_profile` TYPE minmax GRANULARITY 1,
    INDEX `bloom_filter_$ai_trace_id` `mat_$ai_trace_id` TYPE bloom_filter(0.001) GRANULARITY 2,
    INDEX minmax_mat_historical_migration mat_historical_migration TYPE minmax GRANULARITY 1,
    INDEX `bloom_filter_$ai_session_id` `mat_$ai_session_id` TYPE bloom_filter GRANULARITY 1,
    INDEX `minmax_$ai_session_id` `mat_$ai_session_id` TYPE minmax GRANULARITY 1,
    INDEX `set_$ai_is_error` `mat_$ai_is_error` TYPE set(7) GRANULARITY 1,
    INDEX bloom_filter_distinct_id distinct_id TYPE bloom_filter GRANULARITY 1,
    INDEX minmax_sharded_events_timestamp timestamp TYPE minmax GRANULARITY 1,
    INDEX minmax_historical_migration historical_migration TYPE minmax GRANULARITY 1,
    INDEX `bloom_filter_$ai_prompt_name` `mat_$ai_prompt_name` TYPE bloom_filter GRANULARITY 1,
    INDEX `minmax_$ai_prompt_name` `mat_$ai_prompt_name` TYPE minmax GRANULARITY 1,
    INDEX minmax_mat_name mat_name TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$screen_name` `mat_$screen_name` TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$email` `mat_$email` TYPE minmax GRANULARITY 1,
    INDEX minmax_mat_UserName mat_UserName TYPE minmax GRANULARITY 1,
    INDEX minmax_mat_username mat_username TYPE minmax GRANULARITY 1,
    INDEX minmax_mat_Email mat_Email TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$current_url` `mat_$current_url` TYPE minmax GRANULARITY 1,
    INDEX minmax_mat_Name mat_Name TYPE minmax GRANULARITY 1,
    INDEX minmax_mat_Username mat_Username TYPE minmax GRANULARITY 1,
    INDEX `bloom_filter_$ai_experiment_id` `mat_$ai_experiment_id` TYPE bloom_filter GRANULARITY 1,
    INDEX `minmax_$ai_experiment_id` `mat_$ai_experiment_id` TYPE minmax GRANULARITY 1,
    INDEX `minmax_$session_id_uuid` `$session_id_uuid` TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$exception_values` `mat_$exception_values` TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$exception_types` `mat_$exception_types` TYPE minmax GRANULARITY 1,
    INDEX `minmax_mat_$exception_issue_id` `mat_$exception_issue_id` TYPE minmax GRANULARITY 1
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.events', '{replica}', _timestamp)
PARTITION BY toYYYYMM(timestamp)
ORDER BY (team_id, toDate(timestamp), event, cityHash64(distinct_id), cityHash64(uuid))
SAMPLE BY cityHash64(distinct_id)
SETTINGS index_granularity = 8192
